<?php

$CONSUMER_KEY = 'NPfpUg6ZhXxWkNn1pP2Qqg';
$CONSUMER_SECRET = '9sAPyd-lcbyK0LaRFDZO7KqxnPc';
$TOKEN = 'zPlVYDrFyBXJtWDoTtkRW1hgHEDEEY8S';
$TOKEN_SECRET = 'RwGeRAWEsJ5UD8RWHKKtknLu4is';


$CLIENT_ID = 'WU6z7FsEd1hqqujqFUQXJw';
$CLIENT_SECRET = 'nx1JYHE4BdrUA59YeLiEM219a7q6by7gBNcwE8fez9NiJ9hX6ldFDlTNX39LUogS';
?>